# Site settings
title: A coastal engineer's blog
author: Clint Reyes
  email: clint.reyes.coastal@gmail.com
description: "My personal site / blog"
github_username: clintreyes

# Build settings
markdown: kramdown
theme: minima
